// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in TRCN cooperative member's profile: name, email, phone, TRCN number, department, bank details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select(
      "id, full_name, email, phone, address, date_of_birth, cooperative_id, department, bank_name, account_number"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-accounts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_accounts_default = defineTool2({
  name: "list_my_accounts",
  title: "List my accounts",
  description: "List all cooperative accounts (savings, shares, etc.) belonging to the signed-in member with current balances.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("accounts").select("id, account_type, balance, status, created_at").eq("user_id", ctx.getUserId());
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { accounts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-loans.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_loans_default = defineTool3({
  name: "list_my_loans",
  title: "List my loans",
  description: "List loans (special, trade, normal, long_term) for the signed-in member, including principal, outstanding balance, interest rate, repayment period, and status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("loans").select(
      "id, loan_type, principal_amount, outstanding_balance, interest_rate, repayment_period, status, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { loans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_transactions_default = defineTool4({
  name: "list_my_transactions",
  title: "List my transactions",
  description: "List the signed-in member's recent transactions (deposits, withdrawals, repayments, etc.). Optionally set `limit` (1-100, default 25).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max transactions to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const n = limit ?? 25;
    const { data, error } = await supabaseForUser4(ctx).from("transactions").select("id, type, amount, description, created_at, account_id").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(n);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contributions.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_contributions_default = defineTool5({
  name: "list_my_special_contributions",
  title: "List my special contributions",
  description: "List the signed-in member's special contribution cycles with monthly amount, duration, contributed total, balance, year, and status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("special_contributions").select(
      "id, application_status, monthly_amount, duration_months, contribution_year, total_contributed, balance, approved_date"
    ).eq("user_id", ctx.getUserId()).order("contribution_year", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { special_contributions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dxeavlgrxdmxtgoioooi";
var mcp_default = defineMcp({
  name: "trcn-coop-mcp",
  title: "TRCN Cooperative Society",
  version: "0.1.0",
  instructions: "Read-only tools for a signed-in TRCN Staff Multipurpose Cooperative Society member. Use these to look up the member's profile, accounts, loans, transactions, and special contributions. All calls act as the signed-in user and respect the cooperative's access policies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_accounts_default, list_loans_default, list_transactions_default, list_contributions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
